### ISSUE TITLE
Linux support

### ISSUE THREAD

**Issue by DvaMishkiLapa** [DvaMishkiLapa/VitaOxiPad#11]
Initial support via `uinput` exists in [the file `linux.rs`](https://github.com/DvaMishkiLapa/VitaOxiPad/blob/main/client/packages/vita_virtual_device/src/linux.rs), but was completely unsupported. In addition, the implementation for ViGemBus Windows is far behind.

**Comment by DvaMishkiLapa** [comment]
Crate [input-linux](https://crates.io/crates/input-linux) is broken.
I don't know why, but the push codes are completely inconsistent with what they are supposed to mean.

```rust
            key_event!(report, triangle, ButtonWest),
            key_event!(report, circle, ButtonNorth),
            key_event!(report, cross, ButtonEast),
            key_event!(report, square, ButtonSouth),
```
The code above are _the only valid_ 4 key codes I could find.

Need to look for an alternative.

- [uinput-tokio](https://crates.io/crates/uinput-tokio);
- [evdev](https://crates.io/crates/evdev).

**Comment by DvaMishkiLapa** [comment]
It's possible.

Most likely, the Linux version will always lag behind the Windows version of the client in terms of functionality.

Work on functionality porting is in progress in the branch [linux_support](https://github.com/DvaMishkiLapa/VitaOxiPad/tree/linux_support). There you can also see [README.md](https://github.com/DvaMishkiLapa/VitaOxiPad/tree/linux_support?tab=readme-ov-file#linux-client), where the state of affairs is reflected.

**Comment by saidsay-so** [comment]
The project already supports Linux, actually. Although, the multitouch logic is faulty and should be reworked, perhaps using <https://bitmath.se/org/code/mtdev/> as inspiration.

**Comment by DvaMishkiLapa** [comment]
Closed in https://github.com/DvaMishkiLapa/VitaOxiPad/pull/24
