### ISSUE TITLE
Save and read cli flags from a config file

### ISSUE THREAD

**Issue by santarl** [DvaMishkiLapa/VitaOxiPad#13]
At present, the command-line interface (CLI) is initiated using a positional flag for the IP address, along with optional flags for further configuration.

To enhance the CLI and improve user experience, we can introduce a configuration feature that allows it to read settings from a configuration file instead of relying solely on flags. Additionally, we can implement functionality to read parameters from environment variables. 
The order of precedence for reading these parameters should preferably be:

1. Flags (highest priority)
2. Environment Variables
3. Config File (lowest priority)

This will make the cli less tedious to use.

**Comment by DvaMishkiLapa** [comment]
Closed in #13
