### ISSUE TITLE
Rear touchpad do not work with alt_triggers config

### ISSUE THREAD

**Issue by PartyBreakerTF2** [DvaMishkiLapa/VitaOxiPad#30]
everything works normal for the "standart" configuration but not "alt_triggers", which only seems to affect the rear touchpad

**Comment by DvaMishkiLapa** [comment]
That's right. The `alt_triggers` for PS Vita L1\R1 binds L1\R1, and PS Vita rear digitizer binds L2\R2. What kind of behaviour would you expect?

https://github.com/DvaMishkiLapa/VitaOxiPad/blob/main/README.md#33-configurations

**Comment by DvaMishkiLapa** [comment]
Fixed in https://github.com/DvaMishkiLapa/VitaOxiPad/commit/d97b9d0c81eb7a0e6bd99646992214b37562c093
Check out the new binaries in this [release](https://github.com/DvaMishkiLapa/VitaOxiPad/releases/tag/latest).

**Comment by PartyBreakerTF2** [comment]
All good now, nice work!
